# Generated by Django 5.0.4 on 2024-04-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profile_pics/default.png",
                upload_to="isms-project-main/profile_pics",
            ),
        ),
    ]
