# Generated by Django 5.0.1 on 2025-02-14 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(unique=True)),
                ('current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Matier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(default='DEFAULT_CODE', max_length=10, unique=True)),
                ('is_common', models.BooleanField(default=False, help_text='True if this course is common to all specialties within the Niveau.')),
            ],
        ),
        migrations.CreateModel(
            name='Proffesseur',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Nom_du_Prof', models.CharField(max_length=255)),
                ('numero_tel', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_niveau', models.CharField(choices=[('L1', 'License 1'), ('L2', 'License 2'), ('L3', 'License 3')], max_length=255)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gs_scholar.anneescolaire')),
                ('specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gs_scholar.specialite')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('Matricul', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_etudiant', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('sexe', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gs_scholar.niveau')),
                ('specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gs_scholar.specialite')),
            ],
        ),
        migrations.CreateModel(
            name='Emailtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gs_scholar.niveau')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('name', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('choices', models.TextField(blank=True, help_text='Comma-separated list of choices', null=True)),
                ('question_type', models.CharField(choices=[('radio', 'Radio'), ('input', 'Input')], default='radio', max_length=10)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='gs_scholar.section')),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_semestre', models.CharField(max_length=255)),
                ('order', models.IntegerField(blank=True)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gs_scholar.niveau')),
            ],
            options={
                'unique_together': {('niveau', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('expiration_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gs_scholar.matier')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gs_scholar.proffesseur')),
                ('sections', models.ManyToManyField(blank=True, related_name='questionnaires', to='gs_scholar.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gs_scholar.semestre')),
            ],
        ),
        migrations.AddField(
            model_name='matier',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gs_scholar.semestre'),
        ),
        migrations.AddField(
            model_name='matier',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gs_scholar.specialite'),
        ),
        migrations.CreateModel(
            name='Studentinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matier', models.CharField(max_length=250)),
                ('url', models.URLField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gs_scholar.specialite')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gs_scholar.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Datainserted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matier_code', models.CharField(max_length=10)),
                ('weight', models.IntegerField()),
                ('selected_choice', models.TextField()),
                ('anne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gs_scholar.anneescolaire')),
                ('etudiant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gs_scholar.etudiant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gs_scholar.question')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gs_scholar.questionnaire')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gs_scholar.section')),
                ('specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gs_scholar.specialite')),
            ],
            options={
                'unique_together': {('questionnaire', 'question', 'etudiant', 'anne', 'specialite')},
            },
        ),
    ]
